monkeying around

diff --git a/docker-entrypoint b/docker-entrypoint
--- a/docker-entrypoint
+++ b/docker-entrypoint
@@ -5,9 +5,9 @@ DOCKER_SOCK=/tmp/docker.sock
 TMP_DIR=/tmp/restart
 
 if [ "$1" = 'autoheal' ] && [ -e ${DOCKER_SOCK} ]; then
-  
+  if [ -d $TMP_DIR ]; then
   mkdir $TMP_DIR
-
+  fi
   # https://docs.docker.com/engine/api/v1.25/
 
   # Set container selector
@@ -44,3 +44,27 @@ if [ "$1" = 'autoheal' ] && [ -e ${DOCKER_SOCK} ]; then
 else
   exec "$@"
 fi
+
+E_CONTAINERS=($CONTAINER_LIST)
+R_CONTAINERS=($(curl --no-buffer -s -XGET --unix-socket $DOCKER_SOCK  http://localhost/containers/json |jq -r '.[].Names'  |jq -r .[] | cut -d '/' -f2))
+A_CONTAINERS=($(curl --no-buffer -s -XGET --unix-socket $DOCKER_SOCK  http://localhost/containers/json?all=true |jq -r '.[].Names'  |jq -r .[] | cut -d '/' -f2))
+
+echo "Monitoring for stopped containers"
+while true; do
+  sleep ${CHECK_INTERFAL:=300}
+
+for e_container in ${E_CONTAINERS[@]}; do
+  if [[ $(echo ${A_CONTAINERS[@]} |grep -Ew "${e_container}" | wc -l) -eq 1 ]]; then
+    #echo "container $e_container is in running list for ${A_CONTAINERS[@]}"
+    # get status
+      status=$(curl --no-buffer -s -XGET --unix-socket $DOCKER_SOCK  http://localhost/containers/$e_container/json |jq -r '.State.Status')
+      #echo "$e_container status is $status"
+
+        if [ ! ${status} == "running" ]; then
+        # attempt to start the container
+          echo "starting container $e_container"
+          curl -f --no-buffer -s -XPOST --unix-socket $DOCKER_SOCK http://localhost/containers/${e_container}/start || echo "$(DATE) starting container ${e-container} failed"
+        fi
+  fi
+done
+done   
